### ISSUE TITLE
FIRE/EMS JOB TITLES

### ISSUE THREAD

**Issue by AaronF0216** [x0Z3ro0x/DKG-FiveM-Server#2]
FIRE/EMS 
Job titles need to be changed to fit the ranking structure of the department.

**Comment by x0Z3ro0x** [comment]
[esx_ambulancejob.zip](https://github.com/x0Z3ro0x/DKG-FiveM-Server/files/3500685/esx_ambulancejob.zip)


Unzip it, edit with notepad++. Add the new jobs. Then zip it back up, and re-upload it here.

**Comment by AaronF0216** [comment]
[esx_ambulancejob.zip](https://github.com/x0Z3ro0x/DKG-FiveM-Server/files/3501816/esx_ambulancejob.zip)

Here is the return file should be working after inputted into the server.

**Comment by x0Z3ro0x** [comment]
Pretty close, take a look at the first line in our SQL Query though (Line 3). Inside our () is the data waiting to be accepted. First of which is the Job_Name, that's always the same, no issue there. Next the grade ID. Same no issue there. Followed by Name. This is where you messed up a little.

The Name section and Label section following are not the same. The Name section is for the code and is what the script will use when interacting with you. However the label is the name you will see. I fixed it for you to better work in the EMS script, take a look:

[esx_ambulancejob.zip](https://github.com/x0Z3ro0x/DKG-FiveM-Server/files/3502724/esx_ambulancejob.zip)

None the less, looks good and changes will be live via the next server restart :) 

Note: Esx_Ambulance will not recognize the new jobs until they are coded into it.

**Comment by x0Z3ro0x** [comment]
Oops another error lol. Syntax error this time:

ERROR 1064 (42000) at line 3: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near '('ambulance',4,'lieutenant','Lieutenant',80,'{\"tshirt_2\":0,\"hair_color_1\":5,' at line 6

Operation failed with exitcode 1
11:34:49 Import of C:\Users\Administrator\Desktop\esx_ambulancejob.sql has finished with 1 errors

Perhaps you forgot to close it up with a } bracket?? I will take a look.

**Comment by AaronF0216** [comment]
Thanks lets hope it was just a simple mistake my apologies.

**Comment by x0Z3ro0x** [comment]
I see I see. You forgot the comma's after line 6 and every ending line after. Take a look. Each new line must end in a comma to signal their is more data waiting to be written. The only line that doesn't need one is the very last line since no more data follows.

**Comment by AaronF0216** [comment]
just noticed simple mistake I will get to fixing it now unless you have already stated

**Comment by x0Z3ro0x** [comment]
[esx_ambulancejob.zip](https://github.com/x0Z3ro0x/DKG-FiveM-Server/files/3502761/esx_ambulancejob.zip)

For you to compare just in case you didn't understand. Anyway all better, jobs are in.
